<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="50" started-at="2017-09-12T06:38:24Z" finished-at="2017-09-12T06:38:24Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="50" started-at="2017-09-12T06:38:24Z" finished-at="2017-09-12T06:38:24Z">
      <class name="week4TestNg.TestNgDependsOnMethods">
        <test-method status="FAIL" signature="createLead()[pri:0, instance:week4TestNg.TestNgDependsOnMethods@194a1b5]" name="createLead" duration-ms="18" started-at="2017-09-12T12:08:24Z" finished-at="2017-09-12T12:08:24Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[FAILED]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: FAILED
	at week4TestNg.TestNgDependsOnMethods.createLead(TestNgDependsOnMethods.java:9)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createLead -->
        <test-method status="PASS" signature="duplicateLead()[pri:0, instance:week4TestNg.TestNgDependsOnMethods@194a1b5]" name="duplicateLead" duration-ms="1" started-at="2017-09-12T12:08:24Z" finished-at="2017-09-12T12:08:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- duplicateLead -->
        <test-method status="PASS" signature="mergeLead()[pri:0, instance:week4TestNg.TestNgDependsOnMethods@194a1b5]" name="mergeLead" duration-ms="1" started-at="2017-09-12T12:08:24Z" depends-on-methods="week4TestNg.TestNgDependsOnMethods.createLead" finished-at="2017-09-12T12:08:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- mergeLead -->
      </class> <!-- week4TestNg.TestNgDependsOnMethods -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
